### ISSUE TITLE
Sikuli Convenience Functions - Image path & Open

### ISSUE THREAD

**Issue by maxdule** [glitchassassin/lackey#28]
I don't know where to post these questions so I'll sum up here.

1. Is it possible to open any file using windows explorer directly? For instance:
`App.open('explorer.exe' + file_path)`
was working in Sikuli, but it does not work in Lackey. Explorer itself opens correctly. 
The only way around is using subprocess directly.

2. I can't seem to make `addImagePath(folder_path)`  work - still file not found message displayed for any image within folder. List of image paths displayed by `getImagePath()` is correct though.

**Comment by maxdule** [comment]
I believe that the problem is in setting path when image is not located in current folder. Thus, modifying lines in _RegionMatching.py_ (33-37) from:

`# if not os.path.exists(path):
		#     raise OSError("File not found: {}".format(path))
		# self.path = path
		# self.similarity = 0.7
		# self.offset = Location(0,0)`

to check for every added image path:
```
no_path = True
		for image_path in [Settings.BundlePath] + Settings.ImagePaths:
			full_path = os.path.join(image_path, path)
			if os.path.exists(full_path):
				no_path = False
				break
		if no_path:
		    raise OSError("File not found: {}".format(path))
		else:
		    self.path = full_path
		    self.similarity = 0.7
		    self.offset = Location(0,0)
```

makes code work.

**Comment by glitchassassin** [comment]
Good catch. Adding this to the next hotfix.

**Comment by glitchassassin** [comment]
The ImagePath issue is fixed in v0.4.2a1.

The App() functionality needs quite a bit of cleanup, it's very inconsistent. I'll work on this next.

**Comment by glitchassassin** [comment]
I've made some updates to the App() class to standardize the way it interprets and attaches to processes. These are now in the develop ring and will be moved to master and released after testing.

It now tries to automatically separate the executable from the provided string, checks to see if it exists in the system path, and if so, stores the executable path and provided arguments to be called with `app.open()`. If the string is prefixed with a `+` (like `App("+notepad.exe")`), it calls `self.open()` to launch the command immediately.

If the executable does not exist in the system path, it assumes you meant to provide a window title instead.

There are a few edge cases where this could cause problems. You won't be able to select a window by title if the title is the path of an executable file (unless it has some other string in the title that you could target, like "Sublime Text"). However, it looks like this is the way Sikuli handles the operation.

**Comment by maxdule** [comment]
I am still having an issue where scripts are run remotely using Jenkins - in this case images saved in the location of the script are not being located.

Settings.BundlePath stores jenkins workspace directory, rather than the location of the script itself (as I believe Sikuli does).

I've used workaround by adding image path in scripts locally (where necessary), but do you think that BundlePath setting is correct in this case?

Cheers!

**Comment by glitchassassin** [comment]
I've pushed a change to the `develop` branch that sets BundlePath based on the main script's directory rather than the current working directory (which is what it had been).

I'm assuming your Jenkins workspace launches the script from some path, e.g. `python C:\scripts\automator.py`. If so, this should now set the BundlePath to `C:\scripts\`.

I'll continue testing with this to make sure it doesn't break anything, and if everything looks good it'll be rolled out with the next release.

**Comment by glitchassassin** [comment]
Resolved with latest update.
