### ISSUE TITLE
KeyModifier.SHIFT throws an error.

### ISSUE THREAD

**Issue by jwstolk** [glitchassassin/lackey#46]
type("s", KeyModifier.SHIFT + KeyModifier.CTRL)
KeyError: 'S'  in: \lackey\PlatformManagerWindows.pyc in releaseKey(self, text) line 258

simple workaround:
type("S", KeyModifier.CTRL)
works ok.  (I was trying to do "SaveAs" without thinking what the shift modifier does.)

In feature-ocr branch.
Note that type("s", KeyModifier.SHIFT + KeyModifier.CTRL) did work before I updated lackey.

I did uncomment the sikuliGUI import because I could not solve that dependency. If you can't reproduce, let me know and I'll have another look at my libraries.

**Comment by glitchassassin** [comment]
Will troubleshoot on Monday, but this should be an easy enough fix. It's probably related to some compatibility changes I made in the main development branch a couple releases ago.

**Comment by glitchassassin** [comment]
As expected, this was related to the changes to the type() method (specifically the underlying back end). I've pushed a fix to the `develop` branch. Once it's been tested and released, I'll update the OCR branch.

**Comment by maxdule** [comment]
I can't seem to make sending keyboard {WIN} key working. Are these maybe related?

**Comment by glitchassassin** [comment]
Looks like that was an issue introduced with the `keyboard` module. The definition for `{WIN}` should be `"win"`, not `"left windows"`. I've pushed a change to the `develop` ring.

**Comment by glitchassassin** [comment]
This has been fixed in the latest release.

**Comment by maxdule** [comment]
I still can't make this {WIN} key working in updated (0.5.3) version. I've tried both on Win7 and Win10 machines, am I doing something wrong?  

I know that Sikuli had a bug related to [Win key](https://bugs.launchpad.net/sikuli/+bug/836453) and that typing Win key is not possible within type method (for just typing the Win key itself, without modifiers), but that keyDown and keyUp methods should be used instead. Should type work in Lackey?

Additionally, I've had issues with following keys - Key.PRINTSCREEN & Key.COMMAND -> typing those in text editor results in typing empty curly braces - {}.

One more question, are the modifiers+brackets supposed to work with new changes? E.g. typing "+(abc)" results in actually seeing "+(abc)" typed, instead of "ABC" (input string in caps).

**Comment by glitchassassin** [comment]
Sorry, I was referring to the original issue. The `{WIN}` fix is in the develop ring. I pushed out the release before I got your note about the `{WIN}` key.

The other issues you report look like key mapping errors. Please open a new issue for this and I'll fix these for the next update.

Thanks!
